version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      - 'POSTGRES_DB=food-to-save'
      - 'POSTGRES_USER=test'
      - 'POSTGRES_PASSWORD=test'
    ports:
      - '5431:5432'
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6378:6379"
    tty: true
  api:
    container_name: foodtosave-api
    image: foodtosave
    depends_on: [ postgres, redis ]
    environment:
      - "DATABASE_HOST=postgres"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_TTL=10"
    ports:
      - '8080:8080'